<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RollForward>Major</RollForward>
    <StartupObject>WinBMD2.Program</StartupObject>
    <UseWindowsForms>true</UseWindowsForms>
    <MyType>WindowsFormsWithCustomSubMain</MyType>

    <RootNamespace>WinBMD2</RootNamespace>
    <AssemblyName>WinBMD2</AssemblyName>

    <Product>WinBMD2</Product>
    <Title>WinBMD2</Title>
    <Version>20.0.1</Version>
    <Company>FreeBMD</Company>
    <Copyright>© FreeBMD</Copyright>

    <ApplicationIcon>icon\WinBMD2.ico</ApplicationIcon>

    <OptionStrict>On</OptionStrict>
    <OptionExplicit>On</OptionExplicit>
    <OptionInfer>On</OptionInfer>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="HelpTopics\Help_About.rtf" />
    <None Remove="HelpTopics\Help_Directives.rtf" />
    <None Remove="HelpTopics\Help_Files.rtf" />
    <None Remove="HelpTopics\Help_FindingScans.rtf" />
    <None Remove="HelpTopics\Help_GettingStarted.rtf" />
    <None Remove="HelpTopics\Help_Grid.rtf" />
    <None Remove="HelpTopics\Help_HeaderForm.rtf" />
    <None Remove="HelpTopics\Help_KeyboardShortcuts.rtf" />
    <None Remove="HelpTopics\Help_Options.rtf" />
    <None Remove="HelpTopics\Help_Ruler.rtf" />
    <None Remove="HelpTopics\Help_Scans.rtf" />
    <None Remove="HelpTopics\Help_Transcribing.rtf" />
    <None Remove="HelpTopics\Help_Troubleshooting.rtf" />
    <None Remove="HelpTopics\Help_Verification.rtf" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="HelpTopics\Help_About.rtf" />
    <EmbeddedResource Include="HelpTopics\Help_Files.rtf" />
    <EmbeddedResource Include="HelpTopics\Help_HeaderForm.rtf" />
    <EmbeddedResource Include="HelpTopics\Help_KeyboardShortcuts.rtf" />
    <EmbeddedResource Include="HelpTopics\Help_Options.rtf" />
    <EmbeddedResource Include="HelpTopics\Help_Ruler.rtf" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="HelpTopics\Help_Directives.rtf" />
    <EmbeddedResource Include="HelpTopics\Help_FindingScans.rtf" />
    <EmbeddedResource Include="HelpTopics\Help_GettingStarted.rtf" />
    <EmbeddedResource Include="HelpTopics\Help_Grid.rtf" />
    <EmbeddedResource Include="HelpTopics\Help_Scans.rtf" />
    <EmbeddedResource Include="HelpTopics\Help_Transcribing.rtf" />
    <EmbeddedResource Include="HelpTopics\Help_Troubleshooting.rtf" />
    <EmbeddedResource Include="HelpTopics\Help_Verification.rtf" />
  </ItemGroup>

  <ItemGroup>
    <Import Include="System.Data" />
    <Import Include="System.Drawing" />
    <Import Include="System.Windows.Forms" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="My Project\Resources.Designer.vb">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="WinBMDResources.Designer.vb">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>WinBMDResources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="My Project\Resources.resx">
      <CustomToolNamespace>My.Resources</CustomToolNamespace>
      <Generator>VbMyResourcesResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.vb</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="WinBMDResources.resx">
      <CustomToolNamespace>My.Resources</CustomToolNamespace>
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>WinBMDResources.Designer.vb</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>


</Project>